### ISSUE TITLE
Please Solve this issue broo

### ISSUE THREAD

**Issue by priyaank2004** [xtekky/Instagram-Account-Creator#4]
Traceback (most recent call last):
  File "C:\Users\Apple 2.0\Downloads\Instagram-Gen-main\Instagram-Gen-main\main.py", line 257, in <module>
    Instagram().main()
  File "C:\Users\Apple 2.0\Downloads\Instagram-Gen-main\Instagram-Gen-main\main.py", line 226, in main
    self.__init_session(session)
  File "C:\Users\Apple 2.0\Downloads\Instagram-Gen-main\Instagram-Gen-main\main.py", line 81, in __init_session
    libcommons_hash = findall(
IndexError: list index out of range
>>>

**Comment by skriptk** [comment]
I am having the exact same issue

C:\Users\stone\Desktop\Instagram-Gen-main>py main.py
Traceback (most recent call last):
  File "C:\Users\stone\Desktop\Instagram-Gen-main\main.py", line 257, in <module>
    Instagram().main()
  File "C:\Users\stone\Desktop\Instagram-Gen-main\main.py", line 226, in main
    self.__init_session(session)
  File "C:\Users\stone\Desktop\Instagram-Gen-main\main.py", line 81, in __init_session
    libcommons_hash = findall(
                      ^^^^^^^^
IndexError: list index out of range
